browser=chrome
Url=https://stage-orders.mutualdrug.com/sign-in
jsonPath=\\target\\sample.json
jvmFile=\\target
userName=vinoth@datacaliper.com
passWord=Demo@1234
adminUserName=bramamurthy@mutualdrug.com
adminPassword=Demo@1234
signUpUserName=mihar51318@lushosa.com
signUpPassword=Test1234
memberUserName=kumarsangatest@gmail.com
memberPassWord=Test1234
memberNewPassWord=Test@1234